### ISSUE TITLE
Tela de Cadastro

### ISSUE THREAD

**Issue by Benedito-Dev** [Benedito-Dev/Senac-UC5#10]

**Comment by Benedito-Dev** [comment]
Criar um Formulario de Login e De Cadastro Funcional

**Comment by EricBackEnd** [comment]
Quer um pai?

**Comment by Benedito-Dev** [comment]
Adicionar os novos na validação de dados, e acresentar um botão que abrira outra guia de escolha de planos, pagina na qual sera passada pra outra pessoa

**Comment by EricBackEnd** [comment]
Concluído.
Obs: não quis me arriscar em fazer a parte dos dados pro banco de dados só fiz a validação
